additionalRepositories:
  - url: https://github.com/gitpod-io/template-agda
  - url: https://github.com/gitpod-io/template-amazonlinux
  - url: https://github.com/gitpod-io/template-astro
  - url: https://github.com/gitpod-io/template-c
  - url: https://github.com/gitpod-io/template-clojure
  - url: https://github.com/gitpod-io/template-coq
  - url: https://github.com/gitpod-io/template-cpp
  - url: https://github.com/gitpod-io/template-datasette
  - url: https://github.com/gitpod-io/template-docker-compose
  - url: https://github.com/gitpod-io/template-dotnet-core-cli-csharp
  - url: https://github.com/gitpod-io/template-elixir
  - url: https://github.com/gitpod-io/template-fedora
  - url: https://github.com/gitpod-io/template-flutter
  - url: https://github.com/gitpod-io/template-gitpod-sxs-codespaces
  - url: https://github.com/gitpod-io/template-golang-cli
  - url: https://github.com/gitpod-io/template-golang-cli-tabnine
  - url: https://github.com/gitpod-io/template-grain
  - url: https://github.com/gitpod-io/template-haskell
  - url: https://github.com/gitpod-io/template-haskell-nix
  - url: https://github.com/gitpod-io/template-hugo
  - url: https://github.com/gitpod-io/template-hy
  - url: https://github.com/gitpod-io/template-ibm-i
  - url: https://github.com/gitpod-io/template-ihp
  - url: https://github.com/gitpod-io/template-jetbrains-clion
  - url: https://github.com/gitpod-io/template-jetbrains-datagrip
  - url: https://github.com/gitpod-io/template-jetbrains-goland
  - url: https://github.com/gitpod-io/template-jetbrains-intellij-idea
  - url: https://github.com/gitpod-io/template-jetbrains-phpstorm
  - url: https://github.com/gitpod-io/template-jetbrains-pycharm
  - url: https://github.com/gitpod-io/template-jetbrains-rider
  - url: https://github.com/gitpod-io/template-jetbrains-rubymine
  - url: https://github.com/gitpod-io/template-jetbrains-webstorm
  - url: https://github.com/gitpod-io/template-julia
  - url: https://github.com/gitpod-io/template-k3s
  - url: https://github.com/gitpod-io/template-meteor
  - url: https://github.com/gitpod-io/template-microsoft-mssql-server
  - url: https://github.com/gitpod-io/template-nextjs
  - url: https://github.com/gitpod-io/template-nix
  - url: https://github.com/gitpod-io/template-nixos
  - url: https://github.com/gitpod-io/template-ocaml
  - url: https://github.com/gitpod-io/template-perl
  - url: https://github.com/gitpod-io/template-php-drupal-ddev
  - url: https://github.com/gitpod-io/template-php-laravel-mysql
  - url: https://github.com/gitpod-io/template-python-django
  - url: https://github.com/gitpod-io/template-python-django-tabnine
  - url: https://github.com/gitpod-io/template-python-flask
  - url: https://github.com/gitpod-io/template-python-flask-tabnine
  - url: https://github.com/gitpod-io/template-ruby-on-rails-postgres
  - url: https://github.com/gitpod-io/template-rust-cli
  - url: https://github.com/gitpod-io/template-scala
  - url: https://github.com/gitpod-io/template-scala-old
  - url: https://github.com/gitpod-io/template-sveltejs
  - url: https://github.com/gitpod-io/template-sveltekit
  - url: https://github.com/gitpod-io/template-tailscale
  - url: https://github.com/gitpod-io/template-template
  - url: https://github.com/gitpod-io/template-terraform-aws
  - url: https://github.com/gitpod-io/template-tlaplus
  - url: https://github.com/gitpod-io/template-typescript-deno
  - url: https://github.com/gitpod-io/template-typescript-node
  - url: https://github.com/gitpod-io/template-typescript-node-tabnine
  - url: https://github.com/gitpod-io/template-typescript-react
  - url: https://github.com/gitpod-io/template-typescript-vue
  - url: https://github.com/gitpod-io/template-unison
  - url: https://github.com/gitpod-io/template-wordpress
  - url: https://github.com/gitpod-io/template-x11-vnc
  - url: https://github.com/gitpod-io/template-yasm

workspaceLocation: ./template-all/.code-workspace
